#global testerror "Err0421"
func main()->rune { return '1'; }
#assert(main() / '1')
