#global testerror "Err0091"

#test
{
    // Display the sum
    print("The sum of {0} and {1} is {2}")
}
