#global testerror "Err0549"

func toto()
{
    const B = 1
    const A = catch B
}
