#global testerror "Err0424"

func toto()
{
    const B = 1
    const A = throw B//catch B
}
